### ISSUE TITLE
Query params support

### ISSUE THREAD

**Issue by divarvel** [mgattozzi/github-rs#130]
I'm not really sure about how query params are supposed to be handled.
[This](https://github.com/mgattozzi/github-rs/blob/master/docs/design.md#macros) part of the doc seems to imply query params are meant to be handled with macros (unfortunately the doc looks a bit out of date, as the examples don't really match with what's in the files).

I've tried this <https://github.com/divarvel/github-rs/commit/48cf57972c31a2277216d9347b173145535503c9> but it fails with the following error
```
¬  github-rs git:(get-issues-by-state)  cargo build
warning: unused manifest key: workspaces
   Compiling github-rs v0.6.1 (file:///Users/clementd/Projects/perso/github-rs)
error: no rules expected the token `|=`
   --> src/repos/get.rs:228:9
    |
228 |         |=> comments -> IssuesComments
    |         ^^

error: aborting due to previous error

error: Could not compile `github-rs`.

To learn more, run the command again with --verbose.
```

Also, how are multiple query params handled? The only occurences of `|?>` I've found are in the macro definition, in the doc and in the `repos/get.rs` file.

Is it possible to just give a `Map<String,Vec<String>>` when issuing a get request?

**Comment by mgattozzi** [comment]
If you look at this commit -> https://github.com/mgattozzi/github-rs/commit/be41a90a16abf12c5e5d0ce0ff11eaecff994ba7

You can see the details of how this all works. You should just be able to add multiple |?> on to it for it to work and add the query parameters. The `from` generated code handles if you already had a parameter specified before or not.

Try swapping the |=> to before the other calls. If you look here -> https://github.com/mgattozzi/github-rs/blob/master/src/macros.rs#L242

At the macro definition it has an order that's required in the tokens in order to generate all the implementations.

**Comment by divarvel** [comment]
The order was indeed the issue, if anyone else runs into the same issue, the macro code says:
`|=> a -> B` *then* `|` *then* `|=> a -> b = C`, *then* `|?>`

**Comment by mgattozzi** [comment]
@divarvel glad that was the case. At some point I'd like to get it working using `$something: tt` for recursive macros and so that the order won't matter but that's a lot of work I don't really want to do right now for little gain.
