### ISSUE TITLE
Evaluate replacing Hyper by reqwest

### ISSUE THREAD

**Issue by aochagavia** [mgattozzi/github-rs#15]
I just stumbled upon this library, so take this with a grain of salt.

It seems to me that you are using hyper only to perform simple requests, so maybe it would make sense to use reqwest instead. A big benefit from this is that the user no longer needs openssl to be installed on the system (unless you are on Linux), because reqwest relies on the native tls implementation (provided by the `native-tls` crate). This would be a great win for Windows users (eg. myself), since installing openssl is cumbersome.

In case you think this is useful I would like to provide a PR for it!

**Comment by mgattozzi** [comment]
I'm looking towards switching Hyper to 0.10 which removes the openssl dependency would should make your windows problem go away. It was a big blocker as well since it was using a an old version of openssl-sys but other crates used newer versions causing conflicts. If you look [here](https://github.com/mgattozzi/github-rs/blob/master/src/requests.rs#L68-L80) you'll see that I need to set some custom headers and some other things that reqwest doesn't have the ability to do. The reason being is that these headers including authorization are needed to interface with github. I'm in the process of doing that replacement [on this branch](https://github.com/mgattozzi/github-rs/tree/0.4) but haven't gotten it to work just yet.

**Comment by aochagavia** [comment]
Ok, thanks for your reply!

**Comment by mgattozzi** [comment]
@aochagavia thanks for bringing it up! It's nice to know people are using the library so I'll work on it this week and push a 0.4 hopefully

**Comment by mgattozzi** [comment]
@aochagavia I just pushed 0.4 to crates.io it uses rustls under the hood so it's a native rust dependency meaning you won't need openssl at all! Enjoy!

**Comment by aochagavia** [comment]
Great! Thanks
