### ISSUE TITLE
Doesn't compile on stable

### ISSUE THREAD

**Issue by kpcyrd** [mgattozzi/github-rs#44]
```
   Compiling github-rs v0.4.0
error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/github-rs-0.4.0/src/lib.rs:2:1
  |
2 | #![feature(custom_derive, plugin)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The custom_derive is probably not needed anymore as serde is compatible with rust stable. The library in master looks a lot different from 0.4.0, I'd love to have a new version available on crates.io soon-ish :)

**Comment by mgattozzi** [comment]
@kpcyrd I'm not sure if I had pushed a stable version to crates.io, as there was a time where I was dependent on nightly. I'm hoping for this to work on stable soon as well! There's two blocking issues right now: #32 and #23. #32 is the big one since it's what's keeping the current master branch on nightly. #23 is what's preventing any kind of upload to crates.io with a new version since it's a git dependency. The good news is that pub(restricted) will be in the new stable release in a week or two! If you can I'd recommend working with the current git branch as this will be the design going forward with github-rs. It's quite usable and provides a custom endpoint function in case the library doesn't cover your use case yet.

I'm hoping to push a version as soon as I can. I'm itching to get it up and announce some of the big changes!

**Comment by mgattozzi** [comment]
Hey @kpcyrd I went to a branch I still have up that was the last commit before the new redesign. I've pushed the changes to crates.io as version 0.4.1! That should solve any problems you might have been having with compilation for now. Though the upcoming update will be quite a break. If this doesn't solve your issue please let me know!

**Comment by kpcyrd** [comment]
@mgattozzi thanks a lot!

**Comment by mgattozzi** [comment]
@kpcyrd you're welcome!
