### ISSUE TITLE
Docs state to use version 0.5, however that doesn't seem to exist

### ISSUE THREAD

**Issue by EwanValentine** [mgattozzi/github-rs#50]
In the docs, it says to use... 

```
[dependencies]
github-rs = "0.5"
```

However, when I run `cargo install` I get... 
```
Caused by:
  no matching package named `github-rs` found (required by `pralert`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.5
versions found: 0.4.1, 0.4.0, 0.3.0, ...
```

**Comment by EwanValentine** [comment]
As a side note, when I use `0.4` I get: 

```
2 | use github_rs::client::Github;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `client` in `github_rs`
```

**Comment by mgattozzi** [comment]
Hey @EwanValentine I'm sorry about that. The current branch has 0.5 in preparation for the launch at some point when Hyper 0.11 and pub(restricted) are out. As such the docs are ahead of the current implementation. The change from 0.4 to 0.5 is a huge breaking change but it's not able to release because of those blocking issues. For the 0.4 code you want this to make requests: https://docs.rs/github-rs/0.4.1/github_rs/github/struct.Client.html. You'll then want to import the traits for access to certain functions.

If you want to know why and how all of this changed I [wrote about it here](https://mgattozzi.com/refactor-rust). Does this help you out at all?

**Comment by EwanValentine** [comment]
Gotcha, thank you! :)

**Comment by mgattozzi** [comment]
Awesome! I'll be pinging anyone who was expecting to use 0.5 when it releases which is at the earliest when the next stable release of Rust comes out.

**Comment by chenshuiluke** [comment]
Hey, do you mind pinging me too? @mgattozzi

**Comment by mgattozzi** [comment]
@chenshuiluke will do!

**Comment by mgattozzi** [comment]
@chenshuiluke and @EwanValentine I just wanted to let you know 0.5 has finally been released now that all the blocking issues are out of the way!
