### ISSUE TITLE
Cannot use github-rs 0.5 or 0.4 with cargo

### ISSUE THREAD

**Issue by CameronDiver** [mgattozzi/github-rs#57]
Using the example from the README, I added 
```
[dependencies]
github-rs = "0.5"
```
to my cargo.toml, and issued a `cargo build`, to be met with:
```
[1] [12:26] ➜  github-events git:(master) ✗ cargo build           
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `^0.5` found for package `github-rs` (required by `github-events`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.4.1, 0.4.0, 0.3.0, ...
```
I then switched to the dependency to 0.4, because apparently that is available, and was
 met with:
```
[12:28] ➜  github-events git:(master) ✗ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `^0.8.0` found for package `webpki` (required by `webpki-roots`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.14.0, 0.13.0, 0.12.1
```

I could be doing something wrong, as I haven't done much rust at all, but it seems like this should work? I tried both with stable 1.18 and nightly 1.20, and got the same results. 

Arch linux, 64bit, cargo version = 0.21.

Let me know if you need any further details, or if I'm doing something wrong :)

**Comment by mgattozzi** [comment]
Hey @CameronDiver you're not crazy. If you go to the crate's page that it mentions [here](https://crates.io/crates/webpki/versions) you can see that the version used was yanked (specifically 0.8.0) but that's most likely from Hyper 0.10 at the time, which is why it fails to compiler. Today the last change I needed to make before I could release 0.5 is over with so I've pushed 0.5 to crates.io. Use that and you should be good to go! Please let me know if you run into bugs or if the docs aren't clear enough!

**Comment by CameronDiver** [comment]
@mgattozzi it seems to be working fine now! Thanks for the quick reply, and the awesome crate ;)

**Comment by mgattozzi** [comment]
@CameronDiver that's great, thanks! I'm always looking for feedback and how it can improve so if you need something just open up an issue and I'll see if it's doable

**Comment by chenshuiluke** [comment]
Hey, thanks man! This is a great lib and I've had no problems using it!

**Comment by mgattozzi** [comment]
@chenshuiluke That's great to hear! The goal was to make it more ergonomic with 0.5 but it's great to see that feedback that it is so thank you!
